# Pandas Migration Agent Configuration

[agent]
name = "PandasMigrationAgent"
version = "2.0.0"
display_name = "Pandas Migration Agent (0.19.2 → 1.1.5)"
description = "Migrates pandas code with direct replacements only"

[migration]
source_version = "0.19.2"
target_version = "1.1.5"
create_backups = true
run_tests = true
generate_report = true
migrate_tests = false  # Don't migrate test files by default

[conda_environments]
"0.19.2" = "py36-1.1.10"
"1.1.5" = "pandas_115_final"

[windows_runtime_paths]
"py36-1.1.10" = "C:\\LocalRuntimes\\py36-1.1.10"

[replacements]
# Direct replacements that work in both versions
rules = [
    ".sort() → .sort_values()",
    ".ix[] → .loc[]/.iloc[]",
    ".valid() → .dropna()",
    "pd.rolling_* → .rolling().*",
    "pd.Panel → aqr.core.panel.Panel",
    "pd.ols() → aqr.stats.ols.OLS()",
    "pd.TimeGrouper → pd.Grouper",
    ".as_matrix() → .values",
]

[exclude_patterns]
# Patterns to exclude from migration
patterns = [
    "__pycache__",
    "*.pyc",
    ".git",
    "venv",
    ".venv",
    "build",
    "dist",
]