agent_name: EnhancedPandasMigrationAgent
version: "1.0"
description: "Automated agent for migrating pandas from 0.19.2 to 1.1.5 with backward compatibility"

# Agent capabilities
capabilities:
  - code_analysis
  - automated_migration
  - test_execution
  - report_generation
  - backup_management

# Prompt configuration
prompts:
  system_prompt_path: "prompts/system_prompt.md"
  user_prompt_template_path: "prompts/user_prompt_template.md"

# Default configuration
default_config:
  auto_rollback_on_failure: true
  run_tests_before_migration: true
  run_tests_after_migration: true
  create_backups: true
  strict_compatibility: true
  max_retries: 3
  test_timeout: 300
  parallel_testing: false

# Pandas version mapping
pandas_versions:
  source: "0.19.2"
  target: "1.1.5"

# Conda environment configuration
conda_environments:
  "0.19.2": "py36-1.1.10"
  "1.1.5": "pandas_115_final"

# Import mappings for deprecated features
custom_import_mappings:
  "pd.Panel": "aqr.core.panel.Panel"
  "pd.ols": "aqr.stats.ols.OLS"
  "pd.stats.ols.OLS": "aqr.stats.ols.OLS"

# File patterns to exclude
exclude_patterns:
  - "__pycache__"
  - "*.pyc"
  - "*.pyo"
  - "venv/"
  - ".venv/"
  - "env/"
  - ".env/"
  - ".git/"
  - ".tox/"
  - "build/"
  - "dist/"
  - "*.egg-info/"

# Supported test frameworks
test_frameworks:
  - pytest
  - unittest
  - nose

# Report formats
report_formats:
  - markdown
  - html
  - json